version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: azureagents-db
    environment:
      - SA_PASSWORD=Your_strong_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_data:/var/opt/mssql
    networks:
      - backendnet

  backend:
    build:
      context: .
      dockerfile: AzureOperationsAgents.UI.Backend/Dockerfile
    container_name: azureagents-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AgentsDb;User Id=sa;Password=Your_strong_password123;
    depends_on:
      - sqlserver
    ports:
      - "8080:80"
    networks:
      - backendnet
      
  scripting:
    build:
      context: .
      dockerfile: AzureOperationsAgents.Agent0Scripting/Dockerfile
    container_name: azureagents-agent0
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AgentsDb;User Id=sa;Password=Your_strong_password123;
    depends_on:
      - sqlserver
    networks:
      - backendnet
      
  classifier:
    build:
      context: .
      dockerfile: AzureOperationsAgents.Agent2EventClassifier/Dockerfile
    container_name: azureagents-classifier
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AgentsDb;User Id=sa;Password=Your_strong_password123;
      - OLLAMA_API=http://ollama:11434
      - ServiceBusConnection=your_service_bus_connection_string
    depends_on:
      - sqlserver
      - ollama
    networks:
      - backendnet
        
        
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - backendnet

  ui:
    build:
      context: ./AzureOperationsAgents.UI.Web
      dockerfile: Dockerfile
      args:
        VITE_MSAL_CLIENT_ID: 22bb92e2-d778-4036-af44-233f4d804243
        VITE_MSAL_AUTHORITY: https://login.microsoftonline.com/cb40d1db-6342-4ccf-b6af-23848df0f8a2
        VITE_MSAL_REDIRECT_URI: http://localhost:3000/dashboard
        VITE_MSAL_SCOPES: api://AzureOperationsAgents/.default
        VITE_HOST_API: http://azureagents-api
    container_name: azureagents-ui
    ports:
      - "3000:80"
    networks:
      - backendnet


volumes:
  sqlvolume:
  ollama_data:

networks:
  backendnet: