# Agent4 Function Deployment Pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'AzureOperationsAgents.Agent4Auditing/AzureOperationsAgents.Agent4Auditing.csproj'
    publishWebProjects: false
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'YourAzureSubscription'
    appType: 'functionAppLinux'
    appName: '${{ variables.app_name_short }}-agent4-auditing'
    package: '$(Build.ArtifactStagingDirectory)/*.zip'