# Infrastructure Deployment Pipeline
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    terraform init
    terraform plan -target=azurerm_function_app.ui_backend -target=azurerm_app_service.web_app -target=azurerm_api_management.api_management -target=azurerm_frontdoor.app_frontdoor
    terraform apply -auto-approve -target=azurerm_function_app.ui_backend -target=azurerm_app_service.web_app -target=azurerm_api_management.api_management -target=azurerm_frontdoor.app_frontdoor
  displayName: 'Deploy UI Backend, Web App, API Management, and FrontDoor'