subscription_id      = ""
    resource_group_name  = "tfstate-rg"
    storage_account_name = "terraformstatestorage"
    container_name       = "terraformstate"
    key                  = "statefile.tfstate"